spring:
  spring:
    datasource:
      url: jdbc:postgresql://db.rldzxwhcqtswrpxkyrxj.supabase.co:5432/postgres
      username: postgres
      password: cjdaud880818
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace